### PR TITLE
Created git / github guide for INN team members

### PR DESCRIPTION
**Pull request by danilito19**

### CODE REVIEW

**Comment by aschweigert** [comment]
Looks great! One small thing, we recently started naming new branches in Largo starting with the issue number they're intended to address. We might want to be a little more clear in this guide re: naming conventions for new branches to be consistent with this style (cc: @rnagle).

Also, we should try to address #64 and either include that here or link to it.

Otherwise, looks good to merge.

**Comment by danilito19** [comment]
Addressed branch naming. We could go ahead and merge and later discuss the anatomy of a good pull request. It probably should be a different doc since this guide is pretty long and can be overwhelming. I tried to be selective about the information.

**Comment by aschweigert** [comment]
this looks good to me, @rnagle can you take a quick look at this before we merge?

**Comment by aschweigert** [comment]
closes #81

**Comment by aschweigert** [comment]
closed with https://github.com/INN/docs/commit/ccc135cc7fffa4a3c636ba1a7610d2b222a8abf0

**Pull request merged**
