### PR TITLE
Additional member job descriptions

### PR DESCRIPTION
**Pull request by danilito19**
Add Pro Publica Design Fellowship and Sunlight Foundation Open Data Project Lead

### CODE REVIEW

**Comment by aschweigert** [comment]
I'd like to reach out to the members and make sure we have permission to include these before merging, can you see if they have contact information on the hiring announcements and just ask to make sure it's ok?

**Comment by danilito19** [comment]
Sounds good - both have contact info so I will reach out.

**Comment by danilito19** [comment]
David from Pro Publica said ok to include their posting. No response from Sunlight Foundation - got an automated "thanks for your interested in the Sunlight Foundation" email, so if anyone has a better contact person, let me know.

**Comment by aschweigert** [comment]
@danilito19 still no word from sunlight?

**Comment by danilito19** [comment]
@aschweigert  None - do you have a good contact person I can reach out to?

**Pull request closed without merging**
